buffy:
  env:
    bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
    gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
    gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors: 6609690
  responders:
    help:
    hello:
      hidden: true
    thanks:
      hidden: true
    basic_command:
      - code_of_conduct:
          command: code of conduct
          description: Show our community Code of Conduct and Guidelines
          messages:
            - "Our CoC: https://github.com/openjournals/joss/blob/master/CODE_OF_CONDUCT.md"
            - "It's adapted from the Contributor Covenant: http://contributor-covenant.org"
            - "Reports of abusive or harassing behavior may be reported to reports@theoj.org"
      - max_test:
          command: test update
          description: Blah Blah Blah
          messages:
            - "blah blah blah blah blah"
            - "aaaaa"
    reviewers_list:
      only: editors
    assign_editor:
      only: editors
    remove_editor:
      only: editors
      no_editor_text: "TBD"
    invite:
      only: editors
    add_remove_assignee:
      only: editors
    list_team_members:
      command: list editors
      team_id: 6609690
      heading: Current recipe editors
    set_value:
      - version:
          only: editors
          sample_value: "v1.0.0"
      - archive:
          only: editors
          sample_value: "10.21105/joss.12345"
    label_command:
      - review_ok:
          only: editors
          command: review successful
          add_labels:
            - reviewed
            - recommend publication
            - pending publication
          remove_labels:
            - ongoing
            - pending review
      - review_nok:
          only: editors
          command: review failed
          add_labels:
            - recommend rejection
    welcome:
      template_file: review_welcome.md
      data_from_issue:
        - bot_name
    close_issue_command:
      only: editors
      command: reject
      add_labels:
        - rejected
    add_remove_checklist:
      template_file: reviewer_checklist.md
      data_from_issue:
        - target-repository
        - author-handle
    wrong_command:
    github_action:
      - draft_paper:
          command: generate pdf
          workflow_repo: ACCESS-NRI/med-recipes
          workflow_name: draft-paper.yml
          workflow_ref: main
          description: Generates the pdf paper
          data_from_issue:
            - branch
            - target-repository
            - issue_id
          mapping:
            repository_url: target-repository


