buffy:
  bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] || 'botsci' %>
  gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
  gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors: 2009411
    eics:
    reviewers:
  responders:
    hello:
    assign_reviewer_n:
    remove_reviewer_n:
      no_reviewer_text: "TBD"

