buffy:
  bot_github_user: <%= ENV['BUFFY_BOT_GH_USER'] %>
  gh_access_token: <%= ENV['BUFFY_GH_ACCESS_TOKEN'] %>
  gh_secret_token: <%= ENV['BUFFY_GH_SECRET_TOKEN'] %>
  teams:
    editors: 3824115
  responders:
    help:
    hello:
    thanks:
    assign_reviewer_n:
      only: editors
    remove_reviewer_n:
      only: editors
      no_reviewer_text: "TBD"
    assign_editor:
      only: editors
    remove_editor:
      only: editors
      no_reviewer_text: "TBD"

