editor_team_id: 2009411
reviewers: https://bit.ly/joss-reviewers
reviewers_signup: http://joss.theoj.org/reviewer-signup.html
responders:
  - AnnoyingResponder
  - GoodbyeResponder
  - WelcomeResponder
